name: "Close or mark stale Pull Requests"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.TOKEN }}
        stale-pr-message: 'Your pull request has not seen any activity for a while, so it will be marked as stale. If no activity is not seen after 7 days, your pull request will be closed and marked as invalid.'
        stale-pr-label: 'stale'
        close-pr-message: 'Unfortunetly, your pull request has not had any activity for the past seven days, so your pull request will be closed'
        days-before-stale: 7
        days-before-close: 7
